# Generated by Django 5.1.6 on 2026-03-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_report_collaborators_report_coordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='steps_to_reproduce',
            field=models.TextField(blank=True),
        ),
    ]
